// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartRecyclingApi.Data;

#nullable disable

namespace SmartRecyclingApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115203802_UtilizadoresRoleNull")]
    partial class UtilizadoresRoleNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartRecyclingApi.Models.PedidoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Data_Criacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status_Pedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Pedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ref_Utilizador")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ref_Utilizador");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("SmartRecyclingApi.Models.ReciclagemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("MatPapel")
                        .HasColumnType("float");

                    b.Property<double?>("MatPlastico")
                        .HasColumnType("float");

                    b.Property<double?>("MatVidro")
                        .HasColumnType("float");

                    b.Property<DateTime?>("data_Reciclagem")
                        .HasColumnType("datetime2");

                    b.Property<long>("ref_Utilizador")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ref_Utilizador");

                    b.ToTable("Reciclagem");
                });

            modelBuilder.Entity("SmartRecyclingApi.Models.UtilizadorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("adesao")
                        .HasColumnType("bit");

                    b.Property<string>("codigo_postal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("data_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pontos")
                        .HasColumnType("int");

                    b.Property<bool?>("status")
                        .HasColumnType("bit");

                    b.Property<int?>("telefone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("SmartRecyclingApi.Models.PedidoModel", b =>
                {
                    b.HasOne("SmartRecyclingApi.Models.UtilizadorModel", "Utilizador")
                        .WithMany("Pedido")
                        .HasForeignKey("ref_Utilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("SmartRecyclingApi.Models.ReciclagemModel", b =>
                {
                    b.HasOne("SmartRecyclingApi.Models.UtilizadorModel", "Utilizador")
                        .WithMany("Reciclagem")
                        .HasForeignKey("ref_Utilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("SmartRecyclingApi.Models.UtilizadorModel", b =>
                {
                    b.Navigation("Pedido");

                    b.Navigation("Reciclagem");
                });
#pragma warning restore 612, 618
        }
    }
}
